### ISSUE TITLE
LDO regulator power-draw

### ISSUE THREAD

**Issue by SloMusti** [IRNAS/gps-tag-lora-addon-hardware#6]
The LDO regulator draws an undesired amount of power in the given situations:

 * 3V3 power applied, no 5V input - 40uA
 * 5V  power applied, LDO curernt is high - 100uA+

Replacing the LDO with a lower power one from TI tps78326 resolves one scenario, where power draw when 5V power is applied is reduced to about 1uA, however when 3V3 power is applied, the draw is 730uA

**Comment by VojislavM** [comment]
done in the v0.2-22S
